name: Helm Chart Release

on:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Package Helm Chart
        run: |
          mkdir -p packaged
          helm package app-chart -d packaged

      - name: Upload Helm Chart
        uses: actions/upload-artifact@v4
        with:
          name: helm-chart
          path: packaged/*.tgz
