replicaCount: 2

image:
  repository: devops-app
  tag: latest
  pullPolicy: Never

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: devops.local

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

persistence:
  enabled: true
  size: 1Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
